### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by atomicra1n** [iuridepaula/portfolio#2]
Hi there,
first off, thank you so much for making this open-source! It's really amazing and helpful.
Second, I wanted to ask if there is any chance at all you could provide installation and deployment instructions? Sorry if this is asking too much but it'd help me a lot, as the website is really advanced and complicated.

Thank you!
-Megami

**Comment by avincodes** [comment]
Hey, @MegamiShin I have been using this repo for quite some time now, so ill help you with what I know.
 
1. First clone this repository to your local machine using git. If you are not familiar with Git, I recommend you to use the GitHub desktop app which can be found [here](https://desktop.github.com/).

2. Next, you need to open the local directory of the cloned repository and run the following command to install NPM.

```
npm install
```

3. Once that is done, you can go ahead and preview it with:

```
npm run serve
```

4. In order to make a production build, use:

```
npm run build
```

5. When doing so, a folder named "dist" will be created within your project directory which contains all the files necessary for deployment.
 
6. Finally, I recommend you to use a hosting service like [Netlify](https://www.netlify.com/) to host this for free.


Please let me know if you have any more questions, or if you need further help!

Thank you, 
**Avin** :octocat:

**Comment by atomicra1n** [comment]
Hi @avincodes 
Thank you so much for the response!
After running npm install, I was sadly met with an error:

```
C:\Users\orelv\Documents\GitHub\portfolio>npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'scrollmagic@2.0.6',
npm WARN EBADENGINE   required: { node: '0.10.x' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.3.1' }
npm WARN EBADENGINE }
npm WARN deprecated set-value@2.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated mixin-deep@1.3.1: Critical bug fixed in v2.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated eslint-loader@2.1.2: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated @hapi/topo@3.1.0: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated vue-analytics@5.16.4: Sorry but vue-analytics is no longer maintained. I would suggest you switch to vue-gtag, with love, the guy who made the package.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated request-promise-native@1.0.7: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated chokidar@2.1.6: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated @hapi/hoek@6.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated @hapi/address@2.0.0: Moved to 'npm install @sideway/address'
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.0.1: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated source-map-resolve@0.5.2: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated @hapi/joi@15.0.3: Switch to 'npm install joi'
npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
npm WARN deprecated svgo@1.2.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated highlight.js@9.15.6: Version no longer supported. Upgrade to @latest
npm WARN deprecated core-js@2.6.5: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path C:\Users\orelv\Documents\GitHub\portfolio\node_modules\fibers
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node build.js || nodejs build.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.14.0 | win32 | x64
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Users\orelv\AppData\Local\Programs\Python\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:399:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\orelv\\Documents\\GitHub\\portfolio\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd C:\Users\orelv\Documents\GitHub\portfolio\node_modules\fibers
npm ERR! gyp ERR! node -v v16.14.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! node-gyp exited with code: 1
npm ERR! Please make sure you are using a supported platform and node version. If you
npm ERR! would like to compile fibers on this machine please make sure you have setup your
npm ERR! build environment--
npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
npm ERR! Alpine users please run: `sudo apk add python make g++`
npm ERR! 'nodejs' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\orelv\AppData\Local\npm-cache\_logs\2022-03-27T20_55_01_712Z-debug-0.log
```

Any ideas as to how I could fix this? Thanks.

**Comment by ineffablesam** [comment]
> Hi @avincodes Thank you so much for the response! After running npm install, I was sadly met with an error:
> 
> ```
> C:\Users\orelv\Documents\GitHub\portfolio>npm install
> npm WARN old lockfile
> npm WARN old lockfile The package-lock.json file was created with an old version of npm,
> npm WARN old lockfile so supplemental metadata must be fetched from the registry.
> npm WARN old lockfile
> npm WARN old lockfile This is a one-time fix-up, please be patient...
> npm WARN old lockfile
> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: 'scrollmagic@2.0.6',
> npm WARN EBADENGINE   required: { node: '0.10.x' },
> npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.3.1' }
> npm WARN EBADENGINE }
> npm WARN deprecated set-value@2.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
> npm WARN deprecated mixin-deep@1.3.1: Critical bug fixed in v2.0.1, please upgrade to the latest version.
> npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
> npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
> npm WARN deprecated eslint-loader@2.1.2: This loader has been deprecated. Please use eslint-webpack-plugin
> npm WARN deprecated @hapi/topo@3.1.0: This version has been deprecated and is no longer supported or maintained
> npm WARN deprecated vue-analytics@5.16.4: Sorry but vue-analytics is no longer maintained. I would suggest you switch to vue-gtag, with love, the guy who made the package.
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated request-promise-native@1.0.7: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
> npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
> npm WARN deprecated har-validator@5.1.3: this library is no longer supported
> npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
> npm WARN deprecated chokidar@2.1.6: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
> npm WARN deprecated @hapi/hoek@6.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
> npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
> npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
> npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
> npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
> npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
> npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
> npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
> npm WARN deprecated @hapi/address@2.0.0: Moved to 'npm install @sideway/address'
> npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
> npm WARN deprecated babel-eslint@10.0.1: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
> npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated source-map-resolve@0.5.2: See https://github.com/lydell/source-map-resolve#deprecated
> npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
> npm WARN deprecated @hapi/joi@15.0.3: Switch to 'npm install joi'
> npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
> npm WARN deprecated buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
> npm WARN deprecated svgo@1.2.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
> npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
> npm WARN deprecated highlight.js@9.15.6: Version no longer supported. Upgrade to @latest
> npm WARN deprecated core-js@2.6.5: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
> npm ERR! code 1
> npm ERR! path C:\Users\orelv\Documents\GitHub\portfolio\node_modules\fibers
> npm ERR! command failed
> npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node build.js || nodejs build.js
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@3.8.0
> npm ERR! gyp info using node@16.14.0 | win32 | x64
> npm ERR! gyp ERR! configure error
> npm ERR! gyp ERR! stack Error: Command failed: C:\Users\orelv\AppData\Local\Programs\Python\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
> npm ERR! gyp ERR! stack   File "<string>", line 1
> npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
> npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
> npm ERR! gyp ERR! stack
> npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:399:12)
> npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
> npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
> npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
> npm ERR! gyp ERR! System Windows_NT 10.0.22000
> npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\orelv\\Documents\\GitHub\\portfolio\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
> npm ERR! gyp ERR! cwd C:\Users\orelv\Documents\GitHub\portfolio\node_modules\fibers
> npm ERR! gyp ERR! node -v v16.14.0
> npm ERR! gyp ERR! node-gyp -v v3.8.0
> npm ERR! gyp ERR! not ok
> npm ERR! node-gyp exited with code: 1
> npm ERR! Please make sure you are using a supported platform and node version. If you
> npm ERR! would like to compile fibers on this machine please make sure you have setup your
> npm ERR! build environment--
> npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
> npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
> npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
> npm ERR! Alpine users please run: `sudo apk add python make g++`
> npm ERR! 'nodejs' is not recognized as an internal or external command,
> npm ERR! operable program or batch file.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\orelv\AppData\Local\npm-cache\_logs\2022-03-27T20_55_01_712Z-debug-0.log
> ```
> 
> Any ideas as to how I could fix this? Thanks.

Same issue with me Please help me

**Comment by ineffablesam** [comment]
> 

Can you  specify your OS version and Node version you used to Run this project ?

**Comment by ineffablesam** [comment]
Hey @MegamiShin ,
Finally i have figured out the solution ,
Here is the Steps that i have followed to Run this application in localhost 

1. Download [NVM windows ](https://github.com/coreybutler/nvm-windows)
2. And install it then Restart your cmd and downgrade your node version to v10.23.0  using `nvm install 10.23.0`
3. then open your CMD with administrator access and type  `nvm use 10.23.0`
4. and the remove `@vue/cli-plugin-eslint": "^x.x.x` from package.json
5. the run the below commands
`npm install `
`npm run serve`
Then you can access the website in http://localhost:8080/

**Comment by atomicra1n** [comment]
@samgeekhere Thank you so much for your time and dedication to help. I seriously appreciate it, it means a lot. 😄 
I will test it when I'm at home in a bit.

**Comment by atomicra1n** [comment]
@samgeekhere It worked! Thank you so much!
