### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by raveeshdev** [iuridepaula/portfolio#3]
../src/fibers.cc:899:32: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>&, v8::Local<v8::Function>&)’
--

**Comment by avincodes** [comment]
@raveeshdev If you can show your error a bit more clearly (Preferably a screenshot of the whole error) I might be able to help! 

Thanks,
Avin :octocat:

**Comment by iuridepaula** [comment]
Since there war no more comments about this error, I'm closing it for now.
