### ISSUE TITLE
Any way to run the website on a local machine?

### ISSUE THREAD

**Issue by NNDEV1** [iuridepaula/portfolio#5]

**Comment by iuridepaula** [comment]
Yes! it is finally running again.
I've made some minor fixes to the failing dependencies and added some missing configurations, so now the project runs.

That said, it is still a very outdated project and I would not recommend you to use this code in any recent project. 
It might be used to research for sure, but if you want to create "scrollable" animations like the ones on this project, please use [GSAP ScrollTrigger](https://greensock.com/scrolltrigger/).

It's much better and easier to learn than what this project was using back in 2018.
