### ISSUE TITLE
Please consider adding a LICENSE

### ISSUE THREAD

**Issue by ankushdharkar** [iuridepaula/portfolio#8]
Your work is really amazing! I would like to use parts of it for creating my own portfolio, if you'd allow it.

Please consider adding a license for it, so visitors can understand what is permitted: [Adding License to Repo](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

**Comment by iuridepaula** [comment]
Thanks for the heads-up @ankushdharkar, license added.
